base_model: meta-llama/Meta-Llama-3.1-8B

plugins:
  - axolotl.integrations.liger.LigerPlugin
liger_rope: true
liger_rms_norm: true
liger_glu_activation: true
liger_fused_linear_cross_entropy: true

strict: false

chat_template: llama3
datasets:
  - path: penfever/allenai_WildChat-1M-Full-Qwen_Qwen2.5-72B-Instruct
    type: chat_template
    split: train[:25%]
    field_messages: conversation
    message_field_role: role
    message_field_content: content
  - path: penfever/mmlu-it
    type: jeopardy
    split: auxiliary_train
  - path: penfever/tulu-3-tulu_v3.9_personahub_math_interm_algebra_20k
    type: chat_template
    split: train
    field_messages: messages
    message_field_role: role
    message_field_content: content

dataset_prepared_path: /scratch/bf996/axolotl/datasets/wildchat-250k-qwen2-72b-mmlu-personahub_math_interm_algebra_20k
val_set_size: 0.02
output_dir: /scratch/bf996/axolotl/outputs/llama-3-8b-wildchat-250k-qwen2-72b-mmlu-personahub_math_interm_algebra_20k

sequence_len: 8192
sample_packing: true
pad_to_sequence_len: true

wandb_project: lm-evals
wandb_entity:
wandb_watch:
wandb_name: Llama-3-8B-WildChat-qwen2-72b-mmlu-personahub_math_interm_algebra_20k
wandb_log_model:
hub_model_id: penfever/Llama-3-8B-WildChat-250k-qwen2-72b-mmlu-personahub_math_interm_algebra_20k


gradient_accumulation_steps: 8
micro_batch_size: 2
num_epochs: 1
optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 2e-5

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
early_stopping_patience:
resume_from_checkpoint:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 100
evals_per_epoch: 0
eval_table_size:
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
  - full_shard
  - auto_wrap
fsdp_config:
  fsdp_limit_all_gathers: true
  fsdp_sync_module_states: true
  fsdp_offload_params: true
  fsdp_use_orig_params: false
  fsdp_cpu_ram_efficient_loading: true
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_transformer_layer_cls_to_wrap: LlamaDecoderLayer
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_backward_prefetch: BACKWARD_PRE
special_tokens:
  pad_token: <|finetune_right_pad_id|>
  eos_token: <|eot_id|>